import type { Layer } from '../types/layer-types';

/**
 * The default HAL design — a red HAL-9000-style eye that ships with the app.
 *
 * Loaded on first run (no saved design in localStorage) in both Design and
 * Present modes, so the app never cold-starts to an empty canvas. Layers are
 * ordered background → foreground. All coordinates assume the standard
 * 500px composite canvas.
 */
export const DEFAULT_HAL_LAYERS: Layer[] = [
  {
    id: 'hal-housing',
    name: 'Housing Ring',
    type: 'shape',
    shapeType: 'circle',
    visible: true,
    opacity: 1,
    blendMode: 'normal',
    scale: 1,
    rotation: 0,
    offsetX: 0,
    offsetY: 0,
    fillType: 'none',
    strokeType: 'gradient',
    strokeWidth: 8,
    strokeGradient: {
      type: 'linear',
      colors: ['#565d6d', '#14161c', '#565d6d'],
      stops: [0, 0.5, 1],
      angle: 135,
    },
    shapeSpecific: { radius: 228 },
  },
  {
    id: 'hal-iris-backdrop',
    name: 'Iris Backdrop',
    type: 'shape',
    shapeType: 'circle',
    visible: true,
    opacity: 1,
    blendMode: 'normal',
    scale: 1,
    rotation: 0,
    offsetX: 0,
    offsetY: 0,
    fillType: 'gradient',
    fillGradient: {
      type: 'radial',
      colors: ['#2b0503', '#160202', '#050101'],
      stops: [0, 0.6, 1],
    },
    strokeType: 'none',
    shapeSpecific: { radius: 222 },
  },
  {
    id: 'hal-eq-outer',
    name: 'Outer Spectrum Ring',
    type: 'equalizer',
    visible: true,
    opacity: 0.9,
    blendMode: 'screen',
    scale: 1,
    rotation: 0,
    offsetX: 0,
    offsetY: 0,
    equalizerSettings: {
      barCount: 96,
      barStyle: 'line',
      barWidth: 2,
      barSpacing: 1,
      barRotation: 0,
      innerRadius: 174,
      maxHeight: 34,
      responseSpeed: 0.7,
      frequencyRange: 'full',
      colorMode: 'gradient',
      primaryColor: '#ff2a00',
      secondaryColor: '#ffa040',
      glowIntensity: 0.6,
      symmetry: 'mirror',
      pulseMode: 'none',
      positionX: 50,
      positionY: 50,
      startAngle: 0,
      endAngle: 360,
      arcMode: false,
    },
  },
  {
    id: 'hal-eq-dots',
    name: 'Inner Dot Ring',
    type: 'equalizer',
    visible: true,
    opacity: 0.85,
    blendMode: 'screen',
    scale: 1,
    rotation: 0,
    offsetX: 0,
    offsetY: 0,
    equalizerSettings: {
      barCount: 64,
      barStyle: 'dot',
      dotSize: 3,
      barWidth: 3,
      barSpacing: 2,
      barRotation: 0,
      innerRadius: 126,
      maxHeight: 26,
      responseSpeed: 0.75,
      frequencyRange: 'mid',
      colorMode: 'gradient',
      primaryColor: '#b81400',
      secondaryColor: '#ff7a20',
      glowIntensity: 0.5,
      symmetry: 'mirror',
      pulseMode: 'none',
      positionX: 50,
      positionY: 50,
      startAngle: 0,
      endAngle: 360,
      arcMode: false,
    },
  },
  {
    id: 'hal-tick-ring',
    name: 'Rotating Tick Ring',
    type: 'shape',
    shapeType: 'circle',
    visible: true,
    opacity: 0.55,
    blendMode: 'screen',
    scale: 1,
    rotation: 0,
    offsetX: 0,
    offsetY: 0,
    fillType: 'none',
    strokeType: 'solid',
    strokeColor: '#ff5a26',
    strokeWidth: 3,
    strokeDasharray: '2 22',
    animation: 'rotate',
    animationSpeed: 0.4,
    shapeSpecific: { radius: 148 },
  },
  {
    id: 'hal-core',
    name: 'Core Eye',
    type: 'shape',
    shapeType: 'circle',
    visible: true,
    opacity: 1,
    blendMode: 'screen',
    scale: 1,
    rotation: 0,
    offsetX: 0,
    offsetY: 0,
    fillType: 'gradient',
    fillGradient: {
      type: 'radial',
      colors: ['#ffe6b8', '#ff7a1a', '#d81e00', '#570800', '#1c0200'],
      stops: [0, 0.18, 0.45, 0.8, 1],
    },
    strokeType: 'none',
    glowIntensity: 0.9,
    glowColor: '#ff3300',
    animation: 'pulse',
    animationSpeed: 0.5,
    shapeSpecific: { radius: 104 },
    audioReactive: {
      enabled: true,
      mappings: [
        {
          audioFeature: 'volume',
          targetProperty: 'scale',
          intensity: 0.5,
          minValue: 1,
          maxValue: 1.25,
          smoothing: 0.6,
        },
        {
          audioFeature: 'bass',
          targetProperty: 'brightness',
          intensity: 0.6,
          minValue: 1,
          maxValue: 1.6,
          smoothing: 0.5,
        },
      ],
    },
  },
  {
    id: 'hal-specular',
    name: 'Lens Reflection',
    type: 'shape',
    shapeType: 'circle',
    visible: true,
    opacity: 0.4,
    blendMode: 'screen',
    scale: 1,
    rotation: 0,
    offsetX: -34,
    offsetY: -42,
    fillType: 'gradient',
    fillGradient: {
      type: 'radial',
      colors: ['#ffffff', 'rgba(255,255,255,0)'],
      stops: [0, 1],
    },
    strokeType: 'none',
    shapeSpecific: { radius: 26 },
  },
];
