import { ParameterDescriptor } from '../IEffect';

export const distortionParameterDescriptors: ParameterDescriptor[] = [
  {
    key: 'distortionType',
    displayName: 'Distortion Type',
    type: 'select',
    defaultValue: 'wave',
    options: [
      { value: 'wave', label: 'Wave' },
      { value: 'ripple', label: 'Ripple' },
      { value: 'twist', label: 'Twist' },
      { value: 'bulge', label: 'Bulge' },
      { value: 'pinch', label: 'Pinch' },
      { value: 'swirl', label: 'Swirl' },
    ],
    description: 'Type of distortion effect',
  },
  {
    key: 'amplitude',
    displayName: 'Amplitude',
    type: 'range',
    defaultValue: 20,
    min: 0,
    max: 100,
    step: 1,
    description: 'Strength of the distortion',
    animatable: true,
  },
  {
    key: 'frequency',
    displayName: 'Frequency',
    type: 'range',
    defaultValue: 0.05,
    min: 0.001,
    max: 0.5,
    step: 0.001,
    description: 'Frequency of the distortion pattern',
    animatable: true,
  },
  {
    key: 'speed',
    displayName: 'Animation Speed',
    type: 'range',
    defaultValue: 1,
    min: 0,
    max: 5,
    step: 0.1,
    description: 'Speed of animated distortion',
    animatable: true,
  },
  {
    key: 'phase',
    displayName: 'Phase Offset',
    type: 'range',
    defaultValue: 0,
    min: 0,
    max: Math.PI * 2,
    step: 0.01,
    description: 'Phase offset for the distortion',
    animatable: true,
  },
  {
    key: 'centerX',
    displayName: 'Center X',
    type: 'range',
    defaultValue: 0.5,
    min: 0,
    max: 1,
    step: 0.01,
    description: 'Horizontal center position (0-1)',
    animatable: true,
  },
  {
    key: 'centerY',
    displayName: 'Center Y',
    type: 'range',
    defaultValue: 0.5,
    min: 0,
    max: 1,
    step: 0.01,
    description: 'Vertical center position (0-1)',
    animatable: true,
  },
  {
    key: 'radius',
    displayName: 'Effect Radius',
    type: 'range',
    defaultValue: 200,
    min: 10,
    max: 500,
    step: 1,
    description: 'Radius of effect for ripple/twist',
    animatable: true,
  },
  {
    key: 'twist',
    displayName: 'Twist Amount',
    type: 'range',
    defaultValue: 0,
    min: -10,
    max: 10,
    step: 0.1,
    description: 'Amount of twist (for twist/swirl effects)',
    animatable: true,
  },
  {
    key: 'direction',
    displayName: 'Wave Direction',
    type: 'select',
    defaultValue: 'horizontal',
    options: [
      { value: 'horizontal', label: 'Horizontal' },
      { value: 'vertical', label: 'Vertical' },
      { value: 'diagonal', label: 'Diagonal' },
      { value: 'radial', label: 'Radial' },
    ],
    description: 'Direction of wave distortion',
  },
  {
    key: 'intensity',
    displayName: 'Intensity',
    type: 'range',
    defaultValue: 1,
    min: 0,
    max: 2,
    step: 0.01,
    description: 'Overall effect intensity',
    animatable: true,
  },
];
