import type { Agent, AgentEvent, AgentSystemState } from './types';

const metrics = (
  tokensUsed: number,
  contextWindow: number,
  latencyMs: number,
  tasksCompleted: number,
  successRate: number,
  queueDepth: number
) => ({
  tokensUsed,
  contextWindow,
  latencyMs,
  tasksCompleted,
  successRate,
  queueDepth,
});

export function createDemoAgents(now = Date.now()): Agent[] {
  return [
    {
      id: 'codex-prime',
      name: 'Codex Prime',
      callsign: 'CX-01',
      role: 'Lead engineer',
      model: 'GPT-5 Codex',
      state: 'thinking',
      stage: 'reason',
      task: 'Agent notification control plane',
      currentStep: 'Mapping event boundaries to visual state',
      progress: 42,
      progressKnown: true,
      workspace: '/workspace/hal-9001',
      branch: 'feature/agent-operations',
      startedAt: now - 11 * 60_000,
      lastSeen: now - 1_300,
      capabilities: ['reasoning', 'code', 'orchestration'],
      metrics: metrics(62_440, 128_000, 820, 18, 98.4, 2),
    },
    {
      id: 'atlas',
      name: 'Atlas',
      callsign: 'AT-07',
      role: 'Runtime verifier',
      model: 'GPT-5 Codex',
      state: 'processing',
      stage: 'execute',
      task: 'Responsive interface verification',
      currentStep: 'Running desktop viewport checks',
      progress: 68,
      progressKnown: true,
      workspace: '/workspace/hal-9001',
      branch: 'feature/agent-operations',
      startedAt: now - 7 * 60_000,
      lastSeen: now - 600,
      capabilities: ['browser', 'tests', 'accessibility'],
      metrics: metrics(31_880, 128_000, 640, 27, 96.9, 1),
    },
    {
      id: 'sentinel',
      name: 'Sentinel',
      callsign: 'SN-12',
      role: 'Security reviewer',
      model: 'GPT-5',
      state: 'waiting',
      stage: 'execute',
      task: 'Notification permission review',
      currentStep: 'Approval required for browser alerts',
      progress: 54,
      progressKnown: true,
      workspace: '/workspace/hal-9001',
      branch: 'audit/notification-bridge',
      startedAt: now - 16 * 60_000,
      lastSeen: now - 8_000,
      capabilities: ['security', 'review', 'policy'],
      metrics: metrics(19_205, 64_000, 1_120, 41, 99.1, 0),
    },
    {
      id: 'forge',
      name: 'Forge',
      callsign: 'FG-04',
      role: 'Build operator',
      model: 'GPT-5 Mini',
      state: 'completed',
      stage: 'deliver',
      task: 'Production bundle analysis',
      currentStep: 'Artifacts ready',
      progress: 100,
      progressKnown: true,
      workspace: '/workspace/hal-9001',
      branch: 'feature/agent-operations',
      startedAt: now - 22 * 60_000,
      lastSeen: now - 42_000,
      capabilities: ['build', 'bundles', 'delivery'],
      metrics: metrics(12_840, 64_000, 410, 63, 97.8, 0),
    },
    {
      id: 'relay',
      name: 'Relay',
      callsign: 'RY-22',
      role: 'Integration runner',
      model: 'GPT-5 Mini',
      state: 'error',
      stage: 'execute',
      task: 'External event stream handshake',
      currentStep: 'WebSocket retry budget exhausted',
      progress: 31,
      progressKnown: true,
      workspace: '/workspace/bridge',
      branch: 'fix/reconnect-backoff',
      startedAt: now - 9 * 60_000,
      lastSeen: now - 64_000,
      capabilities: ['network', 'events', 'integration'],
      metrics: metrics(8_912, 64_000, 2_840, 15, 88.2, 3),
    },
    {
      id: 'archive',
      name: 'Archive',
      callsign: 'AR-30',
      role: 'Context indexer',
      model: 'Local embedding',
      state: 'idle',
      stage: 'intake',
      task: 'Standing by',
      currentStep: 'Context index synchronized',
      progress: 0,
      progressKnown: false,
      workspace: '/workspace/knowledge',
      branch: 'main',
      startedAt: null,
      lastSeen: now - 4_000,
      capabilities: ['memory', 'search', 'retrieval'],
      metrics: metrics(4_120, 32_000, 180, 112, 99.7, 0),
    },
  ];
}

export function createDemoEvents(now = Date.now()): AgentEvent[] {
  return [
    {
      id: 'seed-cognition-map',
      agentId: 'codex-prime',
      kind: 'thought',
      state: 'thinking',
      severity: 'info',
      title: 'State vocabulary resolved',
      detail:
        'Separating cognition, execution, waiting, completion, and failure into distinct visual signals.',
      timestamp: now - 38_000,
      progress: 42,
      task: 'Agent notification control plane',
      acknowledged: true,
      resolved: false,
      source: 'demo',
    },
    {
      id: 'seed-component-read',
      agentId: 'codex-prime',
      kind: 'tool',
      state: 'processing',
      severity: 'trace',
      title: 'Repository topology indexed',
      detail:
        '184 source files classified across rendering, audio, effects, and mode boundaries.',
      timestamp: now - 72_000,
      progress: 34,
      tool: 'rg',
      durationMs: 284,
      acknowledged: true,
      resolved: true,
      source: 'demo',
    },
    {
      id: 'seed-viewport',
      agentId: 'atlas',
      kind: 'tool',
      state: 'processing',
      severity: 'info',
      title: 'Viewport matrix running',
      detail:
        'Desktop, compact laptop, tablet, and mobile layouts queued for visual verification.',
      timestamp: now - 51_000,
      progress: 68,
      tool: 'browser-check',
      acknowledged: false,
      resolved: false,
      source: 'demo',
    },
    {
      id: 'seed-approval',
      agentId: 'sentinel',
      kind: 'approval',
      state: 'waiting',
      severity: 'warning',
      title: 'Desktop alerts need permission',
      detail:
        'Sentinel paused before enabling browser-level completion and failure notifications.',
      timestamp: now - 86_000,
      progress: 54,
      actionable: true,
      acknowledged: false,
      resolved: false,
      source: 'demo',
    },
    {
      id: 'seed-build-complete',
      agentId: 'forge',
      kind: 'completion',
      state: 'completed',
      severity: 'success',
      title: 'Production bundle ready',
      detail:
        'Type-check and optimized Vite build completed. Artifact manifest is available.',
      timestamp: now - 128_000,
      progress: 100,
      durationMs: 13_780,
      artifact: 'dist/',
      actionable: true,
      acknowledged: false,
      resolved: false,
      source: 'demo',
    },
    {
      id: 'seed-relay-error',
      agentId: 'relay',
      kind: 'error',
      state: 'error',
      severity: 'critical',
      title: 'Event bridge disconnected',
      detail:
        'Relay exhausted three reconnect attempts. Operator retry is available.',
      timestamp: now - 64_000,
      progress: 31,
      tool: 'websocket',
      actionable: true,
      acknowledged: false,
      resolved: false,
      source: 'demo',
    },
    {
      id: 'seed-index-ready',
      agentId: 'archive',
      kind: 'system',
      state: 'idle',
      severity: 'success',
      title: 'Context index synchronized',
      detail: 'Archive is ready for retrieval requests with no pending work.',
      timestamp: now - 182_000,
      acknowledged: true,
      resolved: true,
      source: 'demo',
    },
  ];
}

export function createInitialAgentSystemState(
  now = Date.now()
): AgentSystemState {
  return {
    agents: createDemoAgents(now),
    events: createDemoEvents(now),
    selectedAgentId: 'codex-prime',
    filter: 'all',
    simulationEnabled: true,
    soundEnabled: false,
    desktopAlertsEnabled: false,
    connection: 'demo',
    connectionSource: 'demo',
    connectionLabel: 'Local simulation',
    pendingCommands: [],
  };
}
